package: testimonial
version: '2.0.0'
author: 'Alexander Walther, Paul Götz'
supportpage: https://github.com/alexplusde/testimonial

requires:
    php:
        version: '^8.1'
    redaxo: ^5.17
    packages:
        yform/manager: "^4"
        yform_field: "^2.5"

page:
    title: translate:testimonial_title
    icon: rex-icon fa-star
    perm: testimonial[]
    block: system
    prio: 19
    subpages:
        entry:
            title: translate:testimonial_title
            icon: rex-icon fa-star
            perm: testimonial[]
        docs:
            title: translate:testimonial_docs
            subPath: README.md
            icon: rex-icon fa-info-circle
            itemclass: pull-right
            perm: testimonial[docs]
