package: testimonial 
version: '1.0.0-dev' 
author: 'Alexander Walther, Paul Götz' 
supportpage: https://github.com/alexplusde/testimonial 

requires:                       
    php:
        version: '>7.3,<9'
    redaxo: ^5.13              
    packages:                  
        yform: "^4"

page:
    title: translate:testimonial_title    
    icon: rex-icon fa-star

pages:
    testimonial: 
        title: translate:testimonial_title
        icon: rex-icon fa-star  
        perm: testimonial[]               
        subpages:                   
            table:
                title: translate:testimonial_table
                icon: rex-icon fa-star
                perm: testimonial[]
    docs:
        title: translate:testimonial_docs
        subPath: README.md  
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: testimonial[docs]